### ISSUE TITLE
Broken ncbi links

### ISSUE THREAD

**Issue by freddymonteiro** [willblev/assembly_workshop_MA_2016#1]
Hi, 
I noticed your links to the S.cerevisiae S288C (R64) assembly are broken:
According to NCBI the current location of genome sequence is: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz
and gff file lives here ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.gff.gz

**Comment by willblev** [comment]
Thanks Freddy- I've updated the links. Just out of curiosity, how did you
stumble upon my repo?

-Will

**Comment by freddymonteiro** [comment]
Hey! Thanks for such a prompt response.
A professor at the UPF Bioinf. Master’s pointed us to your repo material as a training resource.
Best wishes,
Freddy

**Comment by willblev** [comment]
Ah, that makes sense. Mar and I set up this repo last year- I'm glad that
it's still useful.
